version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.5.9'
    ports:
      - '2181:2181'
# start with only one broker running internaly on port 9092 and externally for other clients and brokers in same cluster on port 9092
  kafka:
    image: 'wurstmeister/kafka:2.13-2.8.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092